### ISSUE TITLE
[RTX 4090] Inference CUDA out of memory issue.

### ISSUE THREAD

**Issue by BupyeongHealer** [ali-vilab/VGen#104]
Thanks for sharing great work!

I use RTX 4090 24GB GPU.
When I do inference using i2vgen-xl, there is an error with CUDA out of memory issue.

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 550.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 319.38 MiB is free. Including non-PyTorch memory, this process has 22.88 GiB memory in use. Of the allocated memory 19.75 GiB is allocated by PyTorch, and 999.90 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

Can I know how to avoid this issue? I already check the batch size, but it was 1.

**Comment by Steven-SWZhang** [comment]
Hello, the current model and code have only been verified on an A100. At the moment, the VRAM on the 4090 is indeed insufficien
