### ISSUE TITLE
[I2VGen-XL] How can i make a much longer video?

### ISSUE THREAD

**Issue by BupyeongHealer** [ali-vilab/VGen#117]
Thanks for sharing great works!

I want to make a much longer video.
How can I make a longer videos?
Can you tell me what the code related to video time is?

**Comment by Steven-SWZhang** [comment]
Hello, you can set the max_frames [here](https://github.com/ali-vilab/VGen/blob/main/configs/i2vgen_xl_infer.yaml#L7) to increase the video duration, but longer durations may reduce performance.
